[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zahir"
version = "0.1.0"
description = "A parallel workflow execution engine with dependency management"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "Róisín Grannell" }
]
license = { text = "MIT" }
keywords = ["workflow", "task", "execution", "parallel", "dependency"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "croniter>=2.0.0",
    "coolname>=2.2.0",
    "tblib>=3.2.2"
]

[project.urls]
Repository = "https://github.com/rgrannell1/zahir"

[tool.hatch.build.targets.wheel]
packages = ["zahir"]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
    "pytest>=8.0.0",
    "freezegun>=1.5.0",
    "pytest-cov>=4.0.0",
    "coverage>=7.2.7",
    "coolname>=2.2.0",
    "ty>=0.0.7",
    "mypy>=1.8.0",
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov",
  "freezegun",
  "coolname",
]

[tool.flake8]
ignore = ["E402"]

[tool.ruff]
target-version = "py313"
